### ISSUE TITLE
E517: No buffers were wiped out: bwipeout 1

### ISSUE THREAD

**Issue by stephane-klein** [lambdalisue/fern-hijack.vim#11]
I have this error:

```
Error detected while processing function <SNR>62_hijack_directory:
line    7:
E517: No buffers were wiped out: bwipeout 1
```

Is this a real bug, or is it an error specific to my configuration?

I have this plugin in my configuration:

```
    use 'lambdalisue/fern-renderer-nerdfont.vim'
    use 'lambdalisue/fern-git-status.vim'
    use 'lambdalisue/fern.vim'
    use 'lambdalisue/fern-hijack.vim'
```

**Comment by stephane-klein** [comment]
@lambdalisue I can fix this issue if I comment this line https://github.com/lambdalisue/fern-hijack.vim/blob/a858da03103a68566525e2ab6b9909e1de8f8604/plugin/fern_hijack.vim#L13

For the moment, I can't understand the purpose of this command.

With this commented line, I don't see any regression.

**Comment by lambdalisue** [comment]
> Is this a real bug, or is it an error specific to my configuration?

I have no idea but I haven't heard this.

> For the moment, I can't understand the purpose of this command.

That command exists for something like #2 or similar.

**Comment by lambdalisue** [comment]
Could you try if https://github.com/lambdalisue/fern-hijack.vim/pull/12 solves the issue? We just suppress errors.

**Comment by stephane-klein** [comment]
> Could you try if https://github.com/lambdalisue/fern-hijack.vim/pull/12 solves the issue

@lambdalisue yes, fixed 👍 

Thanks
