### ISSUE TITLE
Remote authentication required but no callback set

### ISSUE THREAD

**Issue by EricEWeir** [lambdalisue/fern-hijack.vim#14]
I encounter this message when attempting to install the hijack plugin. Is there a way to do so other than by fetch using a plugin manager.

FWIW, I also got the message the first time I tried to install fern. A couple weeks later installation went through without a hitch. My subsequent attempt to install the hijack plugin failed.

I’m a non-coding non-techie vim user, not competent to decipher the message or determine how to respond.

Thanks

**Comment by lambdalisue** [comment]
Closed by same reason with https://github.com/lambdalisue/fern.vim/issues/487

**Comment by EricEWeir** [comment]
Thanks for the attention and clarification. I’ll followup with the developer of the plug-in manager.———————————Eric Weir Atlanta, GA  USA“It has all been combustion.”- W.G. SebaldOn Oct 10, 2023, at 12:37 AM, Λlisue ***@***.***> wrote:﻿
Closed #14 as completed.

**Comment by EricEWeir** [comment]
I got no help from the developer of the plugin manager. 

This morning I noticed that the name of the plugin is `fern-hijack.vim` not `fern-hijack-vim`, which is what I had been using. 

Using the correct name the plugin installed.
