### ISSUE TITLE
Issue #14–“remote authentication required”—solved

### ISSUE THREAD

**Issue by EricEWeir** [lambdalisue/fern-hijack.vim#15]
I got no help from the developer of the plugin manager.

This morning I noticed that the name of the plugin is `fern-hijack.vim` not `fern-hijack-vim`, which is what I had been using.

Using the correct name the plugin installed.

**Comment by lambdalisue** [comment]
So the issue is solved? Good 🎉

**Comment by EricEWeir** [comment]
Curious why an incorrect name would trigger that kind of error message. It really threw me off the track. When an email is bounced back to me I can usually identify the problem promptly.Perhaps if I had shared the precise command I used in trying to install the plugin the error would have been detected by others. My experience is that problems like this are usually due to some simple error on my part. I should be more vigilant for simple errors on my part. ----------------------------------------Eric WeirDecatur, GA ***@***.***"It has all been combustion.”- W.G.  SebaldOn Oct 23, 2023, at 10:30 AM, Λlisue ***@***.***> wrote:﻿
So the issue is solved? Good 🎉
