### ISSUE TITLE
Bug with tabedit

### ISSUE THREAD

**Issue by rainerborene** [lambdalisue/fern-hijack.vim#6]
If you do `tabedit .` it will not open `Fern` in another tab as expected. Instead it will fallback to the current buffer in the current tab.

**Comment by lambdalisue** [comment]
Sorry for late. I haven't watch this repo somehow.

This bug should be fixed by #8 so please try the latest master.

**Comment by arecarn** [comment]
Confirming this works with `:tabedit .`
