### ISSUE TITLE
How to open Fern in Project Drawer automatically?

### ISSUE THREAD

**Issue by carpet-stain** [lambdalisue/fern-hijack.vim#9]
Hello, how can I achieve opening up `fern` using `vim .` on a Project Drawer set up?

**Comment by lambdalisue** [comment]
What you've exactly said is not possible with current implementation while the command is hard-written https://github.com/lambdalisue/fern-hijack.vim/blob/24daa61d69b878947946e84a7711f8b58eae0f50/plugin/fern_hijack.vim#L12

To open fern when Vim startup, see https://github.com/lambdalisue/fern.vim/wiki/Tips#start-fernvim-on-vim-startup-with-a-particular-directory

**Comment by carpet-stain** [comment]
Thank you
